version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: barber-db
    restart: always
    environment:
      POSTGRES_USER: barber
      POSTGRES_PASSWORD: barber
      POSTGRES_DB: barber-fast
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: